use serde::{Deserialize, Serialize};

use crate::{JsonStrMemKV, Part};

/// Represents a tangible output generated by the agent during a task (a file, data structure, or other resource generated).
/// Artifacts are the results or products of the agent's work.
#[derive(Debug, Default, PartialEq, Eq, PartialOrd, Ord, Clone, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Artifact<'a> {
    /// A unique identifier (e.g. UUID) for the artifact within the scope of the task.
    #[serde(borrow)]
    artifact_id: &'a str,
    /// An optional, human-readable name for the artifact.
    #[serde(borrow)]
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<&'a str>,
    /// An optional, human-readable description of the artifact.
    #[serde(borrow)]
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<&'a str>,
    ///  An array of content parts that make up the artifact.
    #[serde(borrow)]
    parts: Vec<Part<'a>>,
    /// Optional metadata for extensions. The key is an extension-specific identifier.
    #[serde(borrow)]
    #[serde(skip_serializing_if = "Option::is_none")]
    metadata: Option<JsonStrMemKV<'a>>,
    /// The URIs of extensions that are relevant to this artifact.
    #[serde(borrow)]
    #[serde(skip_serializing_if = "Option::is_none")]
    extensions: Option<Vec<&'a str>>,
}
