use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::{Artifact, JsonStr, Message, TaskStatus};

///  Represents a single, stateful operation or conversation between a client and an agent.
#[derive(Debug, Default, PartialEq, Eq, PartialOrd, Ord, Clone, Hash, Serialize, Deserialize)]
pub struct Task<'a> {
    /// A unique identifier (e.g. UUID) for the task, generated by the server for a new task.
    #[serde(borrow)]
    id: &'a str,
    /// A server-generated unique identifier (e.g. UUID) for maintaining context across multiple related tasks or interactions.
    #[serde(borrow)]
    context_id: &'a str,
    /// The current status of the task, including its state and a descriptive message.
    #[serde(borrow)]
    status: TaskStatus<'a>,
    /// An array of messages exchanged during the task, representing the conversation history.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    history: Option<Vec<Message<'a>>>,
    /// A collection of artifacts generated by the agent during the execution of the task.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    artifacts: Option<Vec<Artifact<'a>>>,
    /// Optional metadata for extensions. The key is an extension-specific identifier.
    #[serde(borrow)]
    #[serde(skip_serializing_if = "Option::is_none")]
    metadata: Option<BTreeMap<&'a str, JsonStr<'a>>>,
    /// The type of this object, used as a discriminator. Always 'task' for a Task.
    #[serde(borrow)]
    kind: &'a str,
}

impl<'a> Task<'a> {
    pub fn new() -> Self {
        Self {
            kind: "task",
            ..Default::default()
        }
    }
}
